# Generated by Django 6.0.5 on 2026-06-06 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pedido_confirmado', '✅ Pedido confirmado'), ('pedido_cancelado', '❌ Pedido cancelado'), ('venda_concluida', '🎉 Venda concluída'), ('nova_mensagem', '💬 Nova mensagem'), ('produto_editado', '✏️ Anúncio editado'), ('produto_denunciado', '❗ Produto denunciado'), ('produto_removido', '🔒 Anúncio removido'), ('nova_avaliacao', '⭐ Nova avaliação')], max_length=30)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
