# Generated by Django 6.0.5 on 2026-06-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('pedido_recebido', '🛒 Pedido recebido'), ('pedido_confirmado', '✅ Pedido confirmado'), ('pedido_cancelado', '❌ Pedido cancelado'), ('venda_concluida', '🎉 Venda concluída'), ('nova_mensagem', '💬 Nova mensagem'), ('produto_editado', '✏️ Anúncio editado'), ('produto_denunciado', '❗ Produto denunciado'), ('produto_removido', '🔒 Anúncio removido'), ('nova_avaliacao', '⭐ Nova avaliação')], max_length=30),
        ),
    ]
