# Generated by Django 6.0.5 on 2026-06-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_codigoverificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dois_fatores',
            field=models.BooleanField(default=False),
        ),
    ]
