# Generated by Django 6.0.5 on 2026-05-23 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('Eletrônicos', 'Eletrônicos'), ('Esportes', 'Esportes'), ('Livros', 'Livros'), ('Roupas', 'Roupas'), ('Móveis', 'Móveis'), ('Comidas', 'Comidas'), ('Utilidades', 'Utilidades'), ('Acessórios', 'Acessórios')], max_length=50)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
