# Generated by Django 6.0.5 on 2026-05-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_delete_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='vendido',
            field=models.BooleanField(default=False),
        ),
    ]
