# Generated by Django 6.0.5 on 2026-06-01 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_produto_vendido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('GOLPE', 'Suspeita de Golpe ou Fraude'), ('ILEGAL', 'Produto Ilegal ou Proibido'), ('OFENSIVO', 'Conteúdo Ofensivo ou Inadequado'), ('PRECO', 'Preço Abusivo ou Irreal'), ('OUTRO', 'Outro Motivo')], max_length=20)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Detalhes da denúncia')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to='produtos.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_feitas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
