# Generated by Django 6.0.5 on 2026-05-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_status_pedido_vendedor_alter_pedido_comprador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('compra_confirmada', 'Confirmada pelo Comprador'), ('agurdando_confirmacao', 'Aguardando confirmação do comprador'), ('finalizado', 'Finalizado (Venda Confirmada)'), ('cancelamento_solicitado', 'Cancelamento Solicitado pelo Comprador'), ('cancelado', 'Cancelado')], default='pendente', max_length=30),
        ),
    ]
