# Generated by Django 6.0.5 on 2026-05-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('compra_confirmada', 'Confirmada pelo vendedor'), ('aguardando_confirmacao', 'Aguardando confirmação do comprador'), ('finalizado', 'Finalizado (Venda Confirmada)'), ('cancelamento_solicitado', 'Cancelamento Solicitado pelo Comprador'), ('cancelado', 'Cancelado')], default='pendente', max_length=30),
        ),
    ]
